### ISSUE TITLE
Error al Importar Archivo mpp

### ISSUE THREAD

**Issue by AlejOdoo** [idu-bogota/odoo-idu-addons-publico#1]
Buena Tarde
Les Escribo ya que he descargado el modulo del EDT y lo que instalado y configurado  en la version 9 enterprise de odoo, mi duda surge a la hora de importar un archivo mpp me sale el siguiente error  

2016-08-29 21:25:00,760 160 ERROR proyectos openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 901, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 889, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons-extra/project_edt_idu/wizards/importar_mpp.py", line 130, in importar_mpp
    archivo_csv = self.mpp2csv(form, jython, mpp2csv_path, temp_folder)
  File "/opt/odoo/addons-extra/project_edt_idu/wizards/importar_mpp.py", line 282, in mpp2csv
    cwd='/home/'
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

Muchas Gracias Por su ayuda
![screenshot_20160829_152415](https://cloud.githubusercontent.com/assets/18196600/18068150/9523b0ea-6e05-11e6-8801-eba18c32601b.png)

**Comment by cinxgler** [comment]
Saludos, este wizard invoca un script desarrollado en jython, para eso ud debe tener instalado jython 2.7 y en la interfaz de ajustes aparece una opción 'EDT' donde ud indica cual es la ruta donde se encuentra instalado el binario jython y la ruta absoluta donde se encuentra el script mpp2csv, debe verse algo así:

![selection_212](https://cloud.githubusercontent.com/assets/401030/18071593/c6ec4c10-6e1c-11e6-9e8b-b8b4d740d5bb.png)

**Comment by AlejOdoo** [comment]
Buena Noche Muchas Gracias por la pronta respuesta, hice todos los pasos sugeridos , pero me lanza el siguiente error 
2016-08-30 02:27:29,364 908 ERROR proyectos openerp.addons.project_edt_idu.wizards.importar_mpp: command '/usr/bin/jython -Dpython.path=/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/javalib/mpxj.jar:/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/javalib/poi-3.11-20141221.jar:/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/javalib/rtfparserkit-1.1.0.jar /opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/main.py -f /opt/odoo/.local/share/Odoo/filestore/proyectos/project_edt_importar_mpp/2016-08-30_02:27:28.153125-6-b4ubuild_sample_07_(1).mpp.mpp -o /opt/odoo/.local/share/Odoo/filestore/proyectos/project_edt_importar_mpp/2016-08-30_02:27:28.153125-6-b4ubuild_sample_07_(1).mpp.csv' return with error (code 255): "my" variable $jythonHome masks earlier declaration in same scope at /usr/bin/jython line 15.
Traceback (most recent call last):
  File "/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/main.py", line 25, in <module>
    import csv
ImportError: No module named csv

2016-08-30 02:27:29,364 908 ERROR proyectos openerp.addons.project_edt_idu.wizards.importar_mpp: Command '[u'/usr/bin/jython', '-Dpython.path=/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/javalib/mpxj.jar:/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/javalib/poi-3.11-20141221.jar:/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/javalib/rtfparserkit-1.1.0.jar', u'/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/main.py', '-f', '/opt/odoo/.local/share/Odoo/filestore/proyectos/project_edt_importar_mpp/2016-08-30_02:27:28.153125-6-b4ubuild_sample_07_(1).mpp.mpp', '-o', '/opt/odoo/.local/share/Odoo/filestore/proyectos/project_edt_importar_mpp/2016-08-30_02:27:28.153125-6-b4ubuild_sample_07_(1).mpp.csv']' returned non-zero exit status 255
Traceback (most recent call last):
  File "/opt/odoo/addons-extra/project_edt_idu/wizards/importar_mpp.py", line 282, in mpp2csv
    cwd='/tmp/'
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '[u'/usr/bin/jython', '-Dpython.path=/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/javalib/mpxj.jar:/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/javalib/poi-3.11-20141221.jar:/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/javalib/rtfparserkit-1.1.0.jar', u'/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/main.py', '-f', '/opt/odoo/.local/share/Odoo/filestore/proyectos/project_edt_importar_mpp/2016-08-30_02:27:28.153125-6-b4ubuild_sample_07_(1).mpp.mpp', '-o', '/opt/odoo/.local/share/Odoo/filestore/proyectos/project_edt_importar_mpp/2016-08-30_02:27:28.153125-6-b4ubuild_sample_07_(1).mpp.csv']' returned non-zero exit status 255

![screenshot_20160829_213131](https://cloud.githubusercontent.com/assets/18196600/18074103/05c1f346-6e30-11e6-9511-6f264f61c5fe.png)
![screenshot_20160829_213139](https://cloud.githubusercontent.com/assets/18196600/18074105/0a852a74-6e30-11e6-917e-4a628ed2ca1d.png)

**Comment by cinxgler** [comment]
El módulo intentó ejecutar el script de la siguiente forma:

    /usr/bin/jython -Dpython.path=/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/javalib/mpxj.jar:/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/javalib/poi-3.11-20141221.jar:/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/javalib/rtfparserkit-1.1.0.jar /opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/main.py -f /opt/odoo/.local/share/Odoo/filestore/proyectos/project_edt_importar_mpp/2016-08-30_02:27:28.153125-6-b4ubuild_sample_07_(1).mpp.mpp -o /opt/odoo/.local/share/Odoo/filestore/proyectos/project_edt_importar_mpp/2016-08-30_02:27:28.153125-6-b4ubuild_sample_07_(1).mpp.csv

Pero no encontró el módulo csv en el jython. como muestra el error:

    File "/opt/odoo/addons-extra/project_edt_idu/utils/mpp2csv/main.py", line 25, in
    import csv
    ImportError: No module named csv

Debe instalar dentro de las librerias disponibles en jython el modulo csv. Creo que ud instaló jython utilizando el paquete de ubuntu, no se como adicionar librerias a ese jython, yo por lo general instalo el jython que descargo desde http://www.jython.org/downloads.html y hago la instalación con todos las librerias y con pip para jython.

**Comment by AlejOdoo** [comment]
Buenos Dias Nueva mente Agradezco su ayuda, he seguido sus instrucciones tal cual como las expusieron, pero me sale el siguiente mensaje  
![screenshot_20160830_100009](https://cloud.githubusercontent.com/assets/18196600/18094285/8f5fd1dc-6e98-11e6-88f1-0b191acd185b.png)

**Comment by cinxgler** [comment]
Eso es porque esta activo el check **asignar recursos del archivo .mpp**.

Basicamente el sistema va a buscar un usuario que tenga el login o email *builder* , si no lo encuentra le da ese error, entonces lo que debe hacer es crear el usuario builder o desactivar esa opción al cargar el archivo.

**Comment by AlejOdoo** [comment]
cinxgler estoy muy agradecido por toda tu ayuda, ya puedo importar los archivos de project y funciona perfecto, pero tengo una duda en esta importación no veo que importa los tiempos de las tareas, el modulo tiene esta funcionalidad ?

**Comment by cinxgler** [comment]
Acabo de publicar los últimos cambios que he hecho al módulo, puede instalarlos e importar nuevamente un mpp. Quedo atento.

**Comment by AlejOdoo** [comment]
cinxgler Nuevamente Gracias por tu gran ayuda, me funciono a la perfección, pero me surge la siguiente duda, veo que hay un campo nuevo llamado duración. que diferencia hay entre este campo y cantidad planeada. también te comento que voy hacer algunas mejoras sobre este modulo y me gustaría compartirlas con vos ya que este modulo es la base de todo, por ultimo me gustaria saber si de casualidad tienes un manual de usuario del modulo para tener un mejor panorama de este

**Comment by cinxgler** [comment]
hay 2 campos duracion en el EDT, uno es duracion_planeada_dias y el otro es duracion_dias, estos indican la duración en días hábiles, utilizado para la reprogramación; la cantidad esta definido para indicar por ejemplo cantidad de material de obra utilizado en esa tarea, estaría relacionado con el campo product_id que indicaría el detalle del material de obra. 

En cuanto a manual, no tengo ninguno aún, espero hacer uno en los próximos meses. En cuanto a nueva funcionalidad super, te recomiendo crear un nuevo modulo que extienda el que existe para adicionar nuevas funcionalidades propias de tu negocio, de esa forma no existiría clash entre nuestros módulos. Si es corrección de bugs si seria sobre el código del módulo. Quedo atento a cualquier inquietud que tengas al respecto.

**Comment by AlejOdoo** [comment]
cinxgler tengo una duda mas sobre tu modulo como calcularíamos el costo_planeado que es el valor hora del empleado * la Duracion que se importa desde project, en este modulo el campoduracion_planeada_dias 
yo esto desarrollado la extencion del modulo pero no me hereda el modelo hr.employee donde esta el campo timesheet_costo

**Comment by cinxgler** [comment]
La idea del costo y costo_planeado no es para que sea auto calculado, sino que sea indicado por algun otro módulo o aplicación, actualmente estos datos pueden ser cargados del .mpp. El ms-project le puede ayudar a realizar estos cálculos de valores planeados y nosotros en el odoo los tomamos para obtener indicadores basados en el campo  costo, que es el que puede ser diligenciado manualmente ingresando un valor de costo en el project_edt_idu/wizards/registrar_progreso_tarea.py (por el momento oculto en la vista) o como tu lo tienes en mente trayendo el valor de un timesheet. El botón que permite abrir el wizard aparece luego de que haces click en iniciar tarea.

Si no te esta extendiendo el hr.employee, puede ser porque tu módulo no tiene como dependencia explicita el módulo hr.

**Comment by AlejOdoo** [comment]
Buen día. cinxgler te comento que en este desde ayer he montado este modulo en producción en la empresa en la  cual laboro con alguna modificaciones una de ellas es que esta totalmente integrado con el Awesome Timesheet de chrome. quisiera que vieras el trabajo hecho y ademas a provecho para preguntarte como podría hacer para que las duraciones: planeada y real se importaran en horas y no en días como esta actualmente.

**Comment by cinxgler** [comment]
Te envié al personal mis datos de contacto y podemos acordar para ver los cambios. 

En cuanto a cargar las horas, se deben hacer varias modificaciones en el modelo para que los campos no sean *date* sino *datetime* y en el wizard que importa el mpp hacer el ajuste en el formato, también hay que modificar y revisar bien todas las funciones que calculan la duración, progreso y retraso ya que están hechas para manejo de días completos y no por horas.
